config/routes.rb
Rails.application.routes.draw do
   resources :companies
   get 'companies/:id/history', to: 'companies#history', as: 'company_history'

   root 'companies#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

   def self.search(search)
      where("symbol LIKE ?", "#{search}%")
      where("name LIKE ?", "#{search}%")
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  def search
   @companies = Company.none
   if params[:search]
      @companies = Company.search(params[:search]).order("name").limit(20)
   end
  end

  #GET /companies/1/history
  def history
     set_company()
     yahoo_client = YahooFinance::Client.new
     @data = yahoo_client.historical_quotes(@company.symbol, { start_date: Time::now-(24*60*60*30), end_date: Time::now }).map { |e|
        [e.trade_date, '%.3f' % ((e.close.to_f + e.open.to_f + e.high.to_f + e.low.to_f).to_f/4) ]  
     } # 30 days worth of data
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:symbol, :name, :last_sale, :market_cap, :IPO_year, :sector, :industry, :summary_quote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %>
    <%= f.text_field :symbol %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :last_sale %>
    <%= f.text_field :last_sale %>
  </div>

  <div class="field">
    <%= f.label :market_cap %>
    <%= f.text_field :market_cap %>
  </div>

  <div class="field">
    <%= f.label :IPO_year %>
    <%= f.text_field :IPO_year %>
  </div>

  <div class="field">
    <%= f.label :sector %>
    <%= f.text_field :sector %>
  </div>

  <div class="field">
    <%= f.label :industry %>
    <%= f.text_field :industry %>
  </div>

  <div class="field">
    <%= f.label :summary_quote %>
    <%= f.text_field :summary_quote %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/history.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @company.symbol %> - <%= @company.name %>
</h2>
<h3>Average Price for the last 30 days</h3>

<%= line_chart @data, xtitle: "Date", ytitle: "Average Price" %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Name</th>
      <th>last_sale</th>
      <th>market_cap</th>
      <th>IPO_year</th>
      <th>Sector</th>
      <th>Industry</th>
      <th>Summaryquote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.symbol %></td>
        <td><%= company.name %></td>
        <td><%= company.last_sale %></td>
        <td><%= company.market_cap %></td>
        <td><%= company.IPO_year %></td>
        <td><%= company.sector %></td>
        <td><%= company.industry %></td>
        <td><%= company.summary_quote %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Search</h1>

<%= form_tag("", :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
<%= submit_tag "Search" %>
<% end %>

<br>

<% unless @companies.empty? %>

  <div class="table-block">
    <% @companies.each do |company| %>
      <a href="<%= company_history_path(company) %>" class="row-block">
         <div class="cell-block"><%= company.symbol %></div>
         <div class="cell-block"><%= company.name %></div>
      </a>
    <% end %>
</div>

<% else %>

<p>No companies found using with criteria "<%= params[:search] %>".<br>Please try a different search term.</p>

<% end %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @company.symbol %>
</p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>last_sale:</strong>
  <%= @company.last_sale %>
</p>

<p>
  <strong>market_cap:</strong>
  <%= @company.market_cap %>
</p>

<p>
  <strong>IPO_year:</strong>
  <%= @company.IPO_year %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @company.sector %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @company.industry %>
</p>

<p>
  <strong>Summaryquote:</strong>
  <%= @company.summary_quote %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TastyworksCc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>